sudo: required

services:
  - docker

language: go

go:
  - 1.10
  - tip

go_import_path: kubesphere.io/kubesphere

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - dep ensure -v

before_script:
  - docker --version

script:
  - make fmt-check && make build

deploy:
  provider: script
  script: bash install/scripts/docker_push
  on:
    branch: master
